services:
  frontend:
    image: vohoangphuc/jobhuntly-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - jobhuntly-network
    pull_policy: always
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  jobhuntly-network:
    external: true