export interface Company {
    id: number;
    email: string;
    description: string;
    address: string;
    quantity_employee: number;
    location_city: "Hồ Chí Minh" | "Hà Nội" | "Đà Nẵng" | "Cần Thơ" | "Nha Trang";
    username: string;
    status: "active" | "blocked" | "pending";
}

export const mockCompany: Company[] = [
    {
        id: 1,
        email: "company1@gmail.com",
        description: "This is description 1",
        address: "Address 1",
        quantity_employee: 1000,
        location_city: "Hồ Chí Minh",
        username: "Nguyễn Văn A",
        status: "active",
    },
    {
        id: 2,
        email: "company2@gmail.com",
        description: "This is description 2",
        address: "Address 2",
        quantity_employee: 150,
        location_city: "Hà Nội",
        username: "Trần Thị B",
        status: "pending",
    },
    {
        id: 3,
        email: "company3@gmail.com",
        description: "This is description 3",
        address: "Address 3",
        quantity_employee: 300,
        location_city: "Đà Nẵng",
        username: "Lê Văn C",
        status: "blocked",
    },
    {
        id: 4,
        email: "company4@gmail.com",
        description: "This is description 4",
        address: "Address 4",
        quantity_employee: 500,
        location_city: "Cần Thơ",
        username: "Phạm Thị D",
        status: "active",
    },
    {
        id: 5,
        email: "company5@gmail.com",
        description: "This is description 5",
        address: "Address 5",
        quantity_employee: 200,
        location_city: "Nha Trang",
        username: "Vũ Văn E",
        status: "pending",
    },
    {
        id: 6,
        email: "company6@gmail.com",
        description: "This is description 6",
        address: "Address 6",
        quantity_employee: 800,
        location_city: "Hồ Chí Minh",
        username: "Đinh Thị F",
        status: "blocked",
    },
    {
        id: 7,
        email: "company7@gmail.com",
        description: "This is description 7",
        address: "Address 7",
        quantity_employee: 250,
        location_city: "Hà Nội",
        username: "Ngô Văn G",
        status: "active",
    },
    {
        id: 8,
        email: "company8@gmail.com",
        description: "This is description 8",
        address: "Address 8",
        quantity_employee: 400,
        location_city: "Đà Nẵng",
        username: "Bùi Thị H",
        status: "pending",
    },
    {
        id: 9,
        email: "company9@gmail.com",
        description: "This is description 9",
        address: "Address 9",
        quantity_employee: 600,
        location_city: "Cần Thơ",
        username: "Hoàng Văn I",
        status: "active",
    },
    {
        id: 10,
        email: "company10@gmail.com",
        description: "This is description 10",
        address: "Address 10",
        quantity_employee: 700,
        location_city: "Nha Trang",
        username: "Phan Thị J",
        status: "blocked",
    },
    {
        id: 11,
        email: "company11@gmail.com",
        description: "This is description 11",
        address: "Address 11",
        quantity_employee: 350,
        location_city: "Hồ Chí Minh",
        username: "Lý Văn K",
        status: "pending",
    },
    {
        id: 12,
        email: "company12@gmail.com",
        description: "This is description 12",
        address: "Address 12",
        quantity_employee: 900,
        location_city: "Hà Nội",
        username: "Mai Thị L",
        status: "active",
    },
    {
        id: 13,
        email: "company13@gmail.com",
        description: "This is description 13",
        address: "Address 13",
        quantity_employee: 450,
        location_city: "Đà Nẵng",
        username: "Tô Văn M",
        status: "blocked",
    },
    {
        id: 14,
        email: "company14@gmail.com",
        description: "This is description 14",
        address: "Address 14",
        quantity_employee: 550,
        location_city: "Cần Thơ",
        username: "Hứa Thị N",
        status: "active",
    },
    {
        id: 15,
        email: "company15@gmail.com",
        description: "This is description 15",
        address: "Address 15",
        quantity_employee: 1200,
        location_city: "Nha Trang",
        username: "Trịnh Văn O",
        status: "pending",
    },
];