export interface Company {
    id: number;
    email: string;
    description: string;
    address: string;
    quantity_employee: number;
    location_city: ("Hồ Chí Minh" | "Hà Nội" | "Đà Nẵng" | "Cần Thơ" | "Nha Trang")[];
    location_ward: string;
    userId: number;
    status: "active" | "blocked" | "pending";
}

export const mockCompany: Company[] = [
    {
        id: 1,
        email: "company1@gmail.com",
        description: "This is description 1",
        address: "Address 1",
        quantity_employee: 1000,
        location_city: ["Hồ Chí Minh", "Hà Nội"],
        location_ward: "Phường Bến Nghé",
        userId: 1,
        status: "active",
    },
    {
        id: 2,
        email: "company2@gmail.com",
        description: "This is description 2",
        address: "Address 2",
        quantity_employee: 850,
        location_city: ["Đà Nẵng"],
        location_ward: "Phường Hải Châu 1",
        userId: 2,
        status: "pending",
    },
    {
        id: 3,
        email: "company3@gmail.com",
        description: "This is description 3",
        address: "Address 3",
        quantity_employee: 1200,
        location_city: ["Hồ Chí Minh", "Cần Thơ"],
        location_ward: "Phường 3",
        userId: 3,
        status: "blocked",
    },
    {
        id: 4,
        email: "company4@gmail.com",
        description: "This is description 4",
        address: "Address 4",
        quantity_employee: 400,
        location_city: ["Hà Nội"],
        location_ward: "Phường Phúc Xá",
        userId: 4,
        status: "active",
    },
    {
        id: 5,
        email: "company5@gmail.com",
        description: "This is description 5",
        address: "Address 5",
        quantity_employee: 200,
        location_city: ["Nha Trang", "Đà Nẵng"],
        location_ward: "Phường Vĩnh Hòa",
        userId: 5,
        status: "pending",
    },
    {
        id: 6,
        email: "company6@gmail.com",
        description: "This is description 6",
        address: "Address 6",
        quantity_employee: 750,
        location_city: ["Cần Thơ"],
        location_ward: "Phường An Cư",
        userId: 6,
        status: "active",
    },
    {
        id: 7,
        email: "company7@gmail.com",
        description: "This is description 7",
        address: "Address 7",
        quantity_employee: 500,
        location_city: ["Hồ Chí Minh"],
        location_ward: "Phường Tân Định",
        userId: 7,
        status: "blocked",
    },
    {
        id: 8,
        email: "company8@gmail.com",
        description: "This is description 8",
        address: "Address 8",
        quantity_employee: 960,
        location_city: ["Hà Nội", "Nha Trang"],
        location_ward: "Phường Lộc Thọ",
        userId: 8,
        status: "active",
    },
    {
        id: 9,
        email: "company9@gmail.com",
        description: "This is description 9",
        address: "Address 9",
        quantity_employee: 630,
        location_city: ["Đà Nẵng"],
        location_ward: "Phường Hòa Thuận Đông",
        userId: 9,
        status: "pending",
    },
    {
        id: 10,
        email: "company10@gmail.com",
        description: "This is description 10",
        address: "Address 10",
        quantity_employee: 300,
        location_city: ["Hồ Chí Minh", "Đà Nẵng"],
        location_ward: "Phường Nguyễn Thái Bình",
        userId: 10,
        status: "active",
    },
    {
        id: 11,
        email: "company11@gmail.com",
        description: "This is description 11",
        address: "Address 11",
        quantity_employee: 1100,
        location_city: ["Hà Nội", "Cần Thơ"],
        location_ward: "Phường Trần Nguyên Hãn",
        userId: 11,
        status: "blocked",
    },
    {
        id: 12,
        email: "company12@gmail.com",
        description: "This is description 12",
        address: "Address 12",
        quantity_employee: 670,
        location_city: ["Nha Trang"],
        location_ward: "Phường Phước Long",
        userId: 12,
        status: "active",
    },
    {
        id: 13,
        email: "company13@gmail.com",
        description: "This is description 13",
        address: "Address 13",
        quantity_employee: 420,
        location_city: ["Cần Thơ", "Hà Nội"],
        location_ward: "Phường Cái Khế",
        userId: 13,
        status: "pending",
    },
    {
        id: 14,
        email: "company14@gmail.com",
        description: "This is description 14",
        address: "Address 14",
        quantity_employee: 550,
        location_city: ["Đà Nẵng", "Nha Trang"],
        location_ward: "Phường Xuân Hà",
        userId: 14,
        status: "active",
    },
    {
        id: 15,
        email: "company15@gmail.com",
        description: "This is description 15",
        address: "Address 15",
        quantity_employee: 890,
        location_city: ["Hồ Chí Minh"],
        location_ward: "Phường 7",
        userId: 15,
        status: "blocked",
    },
];