name: Build and Deploy React TS App

on:
  push:
    branches: [dev]  
  pull_request:
    branches: [dev]  

concurrency:
  group: fe-deploy
  cancel-in-progress: true

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/jobhuntly-frontend
  DOCKER_TAG: latest
  REMOTE_DIR: ~/jobhuntly-fe

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

      - name: Build React TS
        run: npm run build

  docker-build-push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          build-args: |
            VITE_API_BASE_URL=${{ secrets.PRODUCTION_API_BASE_URL }}
          cache-from: type=gha  
          cache-to: type=gha,mode=max

      - name: Copy docker-compose.yml to EC2 if changed
        if: contains(github.event.commits[0].modified, 'docker-compose.yml') || contains(github.event.commits[0].added, 'docker-compose.yml')
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "${{ env.REMOTE_DIR }}"
          overwrite: true

  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if docker compose version >/dev/null 2>&1; then
              COMPOSE="docker compose"
            else
              COMPOSE="docker-compose"
            fi

            cd ${{ env.REMOTE_DIR }}

            echo "Tạo network (nếu chưa có)..."
            docker network create jobhuntly-network || true

            echo "Pull latest image..."
            $COMPOSE -f docker-compose.yml pull frontend  # Chỉ pull service frontend nếu có nhiều service

            echo "Restart container..."
            $COMPOSE -f docker-compose.yml down frontend || true  # Chỉ down frontend để tránh ảnh hưởng service khác
            $COMPOSE -f docker-compose.yml up -d frontend --remove-orphans

            echo "Check status..."
            $COMPOSE -f docker-compose.yml ps